# Generated by Django 4.2.10 on 2024-04-03 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miembros', '0012_alter_duracionactividad_duracion'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('recibido', models.PositiveIntegerField()),
                ('cambio', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finanzas.ticket')),
            ],
        ),
    ]
