# Generated by Django 4.2.10 on 2024-04-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_ticket_itemticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cambio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recibido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
