# Generated by Django 4.2.10 on 2024-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_ticket_cambio_alter_ticket_recibido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
