# Generated by Django 4.2.10 on 2024-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
    ]
