# Generated by Django 4.2.10 on 2024-03-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'No especificar')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='fotos_miembros/')),
                ('huella_dactilar', models.BinaryField()),
                ('fecha_inicio_membresia', models.DateField()),
                ('estatus_membresia', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Suspendida', 'Suspendida')], max_length=10)),
                ('fecha_fin_membresia', models.DateField()),
                ('actividades', models.ManyToManyField(blank=True, related_name='miembros', to='miembros.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='miembros.miembro')),
            ],
        ),
    ]
