# Generated by Django 4.2.10 on 2024-03-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='huella_dactilar',
            field=models.TextField(blank=True),
        ),
    ]
