# Generated by Django 4.2.10 on 2024-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_alter_miembro_huella_dactilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_miembros/'),
        ),
    ]
