# Generated by Django 4.2.10 on 2024-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_alter_miembro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fecha_fin_membresia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
