# Generated by Django 4.2.10 on 2024-03-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_alter_miembro_fecha_fin_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuracionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(choices=[('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Visita', 'Visita')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duracion_actividades', to='miembros.actividad')),
            ],
        ),
    ]
