# Generated by Django 4.2.10 on 2024-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_duracionactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estatus_membresia',
            field=models.CharField(blank=True, choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], max_length=10, null=True),
        ),
    ]
