# Generated by Django 4.2.10 on 2024-03-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_alter_miembro_estatus_membresia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
