# Generated by Django 4.2.10 on 2024-03-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0009_delete_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembro',
            options={'ordering': ['apellidos', 'nombres']},
        ),
    ]
