# Generated by Django 4.2.10 on 2024-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0011_alter_duracionactividad_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duracionactividad',
            name='duracion',
            field=models.CharField(choices=[('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual'), ('Quincenal', 'Quincenal'), ('Semanal', 'Semanal'), ('Diario', 'Diario')], max_length=10),
        ),
    ]
