# Generated by Django 4.2.10 on 2024-04-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0012_alter_duracionactividad_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=100.0, help_text='Costo de la inscripción para nuevos miembros o miembros inactivos.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estatus_membresia',
            field=models.CharField(blank=True, choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Inactiva', max_length=10),
        ),
    ]
