# Generated by Django 4.2.10 on 2024-06-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0013_configuracion_alter_miembro_estatus_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='actividades',
            field=models.ManyToManyField(default=None, related_name='miembros', to='miembros.actividad'),
        ),
    ]
