# Generated by Django 4.2.10 on 2024-05-29 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.IntegerField(max_length=100)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='configuracionesacesso',
            name='mensaje_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionesacesso',
            name='mensaje_global_str',
            field=models.TextField(blank=True),
        ),
    ]
