# Generated by Django 4.2.10 on 2024-05-29 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_registrovisitas_configuracionesacesso_mensaje_global_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovisitas',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='registrovisitas',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrovisitas',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrovisitas',
            name='miembro',
            field=models.IntegerField(),
        ),
    ]
